# Generated by Django 5.0.14 on 2026-04-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_order_is_paid_order_paid_at_order_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_deducted',
            field=models.BooleanField(default=False, verbose_name='Списано со склада'),
        ),
    ]
